export { client, request } from './client';
export { ApiError } from './errors';
export type {
  MetaResponse,
  User,
  SetupRequest,
  LoginRequest,
  LoginResponse,
  Space,
  SpaceListResponse,
  CreateSpaceRequest,
  Device,
  RegisterDeviceRequest,
  RegisterDeviceResponse,
  Binding,
  BindingListResponse,
  CreateBindingRequest,
  ParentRef,
  OperationDTO,
  SyncRequest,
  OperationResult,
  Change,
  SyncResponse,
  NodeType,
  Node,
  RootSlot,
  NodeListResponse,
  RootSlotListResponse,
  CreateNodeRequest,
  UpdateNodeRequest,
  MoveNodeRequest,
  ActivityAction,
  ActivityEntry,
  ActivityListResponse,
} from './types';
